apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: testapp-svc
spec:
  selector:
    app: testapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
